import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import Searchbar from '../utils/Searchbar'

export default function Home() {
    const [data, setData] = useState('')
    const [latitude, setLatitude] = useState('')
    const [longitude, setLongitude] = useState('')
    const url = `https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&hourly=temperature_2m`

    useEffect(() => {
        fetch(url)
        console.log('hello world')
    }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>Weather Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                <Searchbar />
            </main>

            <footer className={styles.footer}>This is the footer</footer>
        </div>
    )
}
