import Head from 'next/head'
import WeatherHOC from '../components/weatherlist/weatherHOC'

import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Weather Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                <WeatherHOC />
            </main>
        </div>
    )
}
